### ISSUE TITLE
Misc. Fields in Submission Form

### ISSUE THREAD

**Issue by JBlaschke** [ML4FnP/GMRES-Learning#14]
Kevin: 
- [x] Biography for each author (150 word max)
- [x]  download, sign, and upload a scan of the SC20 Consent and Release form 
- [x] Head-shot of each author

Johannes:
- [x] Biography for each author (150 word max)
- [x]  download, sign, and upload a scan of the SC20 Consent and Release form 
- [x] Head-shot of each author

**Comment by JBlaschke** [comment]
As an Issue we can tick things off @kevinluna1 

Is there a due date for this?

**Comment by kevinluna1** [comment]
The official due date for all materials is  10/9/20.
However, since I need to record things through a platform that I get access to *only* after sending in the written materials, it would be ideal to finish these thing by early/mid week next week (10/6/20) at the latest.

**Comment by JBlaschke** [comment]
@kevinluna1 -- I sent you all the materials via email

Closing out this issue
