### ISSUE TITLE
Finalize submissions

### ISSUE THREAD

**Issue by kevinluna1** [ML4FnP/GMRES-Learning#16]
- [x] Poster
- [x] Poster Summary
- [x] Abstract 

**Attempt to accommodate reviewer suggestions/comments
 to final submissions

Reviewer 2)
To improve the poster quality, please add your experimental setup such as experimental platform, serial or parallel (if so, how many nodes used), baseline preconditioning method, etc.

Reviewer 4)
The experimental section needs more explanation. Specifically, which preconditioners were tried and were they picked because they were the best known for the specific scenarios? How much did the training cost? How does the training executioin time compare to the preconditioner? Are there different parallelization opportunities for this versus a preconditioner? How does the performance vary given different datasets?

**Comment by JBlaschke** [comment]
Took me ages to find the link for the conference submission page -- pasting here so I can find it in the future
https://submissions.supercomputing.org/

**Comment by JBlaschke** [comment]
I want to start a slightly longer discussion of the referee comments here:
1. In Figure 1, when the error is below the average, it shows that the current data is good, why not use it for training?
    - Because we're not only trying to minimize the error (in the GMRES sense), but also selecting for N(b) that converge quickly. I suggest putting something like that under the bullet `Crucial` in the `Methodology` section. Eg. `Only those cases where the N(b) resulted in faster-than-average convergence is (x,b) added to the training set. This ensure that the the NN is implicitly trained to maximize convergence rate`
2.  In Figure 1, when the model is ready, it is not clean when you will use the prediction of ML and when use the original method?
    - We _always_ use the NN preconditioner -- right? The output of the preconditioner `N(b)` is always fed into GMRES. This makes our method different from the "learning to solve the linear system" approaches, because we don't need to make decisions about when to not use the NN result. 
3.  Under practical scenario, before your iteration end, how you know the time-to-solution?
    - I don't know what exactly the question is asking.  More often than not, the NN preconditioner will speed up the time to solution. We only know this after the fact -- I.e. after GMRES has reached a target tolerance.

**Comment by stevenireeves** [comment]
Will the rest of us have access to this poster?

**Comment by JBlaschke** [comment]
@stevenireeves once it's done 😛

**Comment by JBlaschke** [comment]
@kevinluna1 I think the poster addressed reviewer 2 -- I'm not sure we've got all of reviewer 4's question. The poster (in its current form shows the training time/variability nicely. But we're still missing:
1. Which preconditioners were tried and were they picked because they were the best known for the specific scenarios? How much did the training cost?
    - The results shown are with respect to un-preconditioned restarted GMRES. We are working on applying it to the algorithm of Cai et al (dx.doi.org/10.4208/cicp.070114.170614a) as it is an important application.
2. Are there different parallelization opportunities for this versus a preconditioner?
    - We're currently working on accelerating distributed-memory GMRES solver based on an AMReX We're currently only exploring data-parallel approaches for training.
There might be room to put those answers (or whatever you think is appropriate) in the poster.
